name:  AI Reviewer in Develop

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Robin AI Reviewer
        uses: Integral-Healthcare/robin-ai-reviewer@v1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_AI_API_KEY: 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
          files_to_ignore: |
            "README.md"
            "assets/*"
            "package-lock.json"
